# this is for local development only
version: '3.9'

services:
  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - ./temp/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_PASSWORD=user_password
      - MYSQL_USER=prisma_user
      - MYSQL_DATABASE=prisma_db